---
apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "^1.15.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      interval: 12h
  values:
    connect:
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
    operator:
      create: true
      watchNamespace: []
