apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "^35.2.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-traefik
        namespace: flux-system
      interval: 12h
  values:
    deployment:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.42.110.200
    ports:
      web:
        port: 80
      websecure:
        port: 443
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: ["web"]
